Repository knative/hack, pull requests merged in 2020-12, with the labels that each got.

#32 Validate usage of knative.dev/hack/shell
  foo/caller_not_allowed_test.go
  shell/project.go
Labels: approved, cla: yes, lgtm, size/M

#31 Improve microbenchmarks.sh script
  microbenchmarks.sh
Labels: approved, cla: yes, lgtm, size/M

#33 Create a go path that points back to the local directory.
  library.sh
Labels: approved, cla: yes, lgtm, size/S

#34 adding github aware tags to new headers
  library.sh
Labels: approved, cla: yes, lgtm, size/M

#36 adding codegen entry point for scripts to help clean dup code up
  codegen-library.sh
  library.sh
Labels: approved, cla: yes, lgtm, size/M

#37 Use testname format for gotestsum command
  library.sh
  test/unit/library-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
