Repository knative/hack, pull requests merged in 2020-11, with the labels that each got.

#10 do not use the sum.golang.org service, too many 410s
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#11 perf tests come from the image
  performance-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#9 allow go_update_deps domain to change
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#5 Move tests to the hack repo
  test/e2e-kind.sh
  test/e2e-tests.sh
  test/e2e/simple_e2e_test.go
  test/library_test.go
  test/presubmit-tests.sh
  test/presubmit-tests.sh.tmpl
  test/unit/e2e-custom-flag-tests.sh
  test/unit/library-tests.sh
  test/unit/presubmit-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
Labels: approved, cla: yes, lgtm, size/XL

#17 the branch name is no longer a valid default for release
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#20 Fix a few more occurrences of divisive language
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#16 Do not output json files since the Golang issue has been fixed
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#24 Use eventing-crds.yaml and eventing-core.yaml for eventing setup
  library.sh
Labels: approved, cla: yes, lgtm, size/S

#19 chore: filter out bogus warnings about symlinks when doing a go mod tidy
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#23 Add latest_version function
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#22 Don't overwrite KO_DOCKER_REPO if already set
  e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#26 Revert "Use eventing-crds.yaml and eventing-core.yaml for eventing setup"
  library.sh
Labels: approved, cla: yes, lgtm, size/S

#29 Unset KO_DOCKER_REPO to allow the tests to use their own
  release.sh
Labels: approved, cla: yes, lgtm, size/XS

#27 Add microbenchmarks scripts
  microbenchmarks.sh
Labels: approved, cla: yes, lgtm, size/M

#30 Shell out package
  shell/assertions_test.go
  shell/executor.go
  shell/executor_test.go
  shell/fail-example.sh
  shell/prefixer.go
  shell/prefixer_test.go
  shell/project.go
  shell/project_test.go
  shell/types.go
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XL
