Repository knative/hack, pull requests merged in 2021-04, with the labels that each got.

#62 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#66 Add debug info for release.sh
  release.sh
  test/e2e-kind.sh
Labels: approved, cla: yes, lgtm, size/XS

#67 Fix default codegen pkg dir
  codegen-library.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#65 Print java and mvn version
  presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
