Repository knative/hack, pull requests merged in 2021-11, with the labels that each got.

#98 Release use `knative-vX.Y.Z` tag and infer go module tag version automatically
  release.sh
  test/unit/release-tests.sh
Labels: cla: yes, lgtm, approved, size/M

#101 fix the latest_version function
  library.sh
  release.sh
Labels: cla: yes, lgtm, approved, size/M

#102 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#103 fix latest version when running in GitHub actions
  library.sh
Labels: cla: yes, lgtm, approved, size/M

#96 Add `wait_until_object_exists` library function
  library.sh
Labels: cla: yes, lgtm, approved, size/S

#105 chore: further explain knative CRD-generation support
  schema/README.md
Labels: cla: yes, lgtm, approved, ok-to-test, kind/documentation, size/S

#104 :bug: Allows to see TAG from build_release func
  release.sh
Labels: cla: yes, lgtm, approved, size/XS, kind/bug

#108 [release-0.26] hack cherry picks
  library.sh
  release.sh
  test/unit/release-tests.sh
Labels: cla: yes, lgtm, approved, size/L

#109 [release-0.25] hack cherry picks
  library.sh
  release.sh
  test/unit/release-tests.sh
Labels: cla: yes, lgtm, approved, size/L

#110 [release-0.24] hack cherry picks
  library.sh
  release.sh
  test/unit/release-tests.sh
Labels: cla: yes, lgtm, approved, size/L

#114 [release-0.26] Pull in missing functions
  library.sh
  release.sh
Labels: cla: yes, lgtm, approved, size/M

#116 [release 0.24] pull in missing functions
  library.sh
  release.sh
Labels: cla: yes, lgtm, approved, size/M

#115 [release 0.25] pull in missing functions
  library.sh
  release.sh
Labels: cla: yes, lgtm, approved, size/M

#117 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#118 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#119 [pre-1.0] Use the TAG unmodified when publishing GitHub releases
  release.sh
Labels: cla: yes, lgtm, approved, size/XS
