Repository knative/hack, pull requests merged in 2021-03, with the labels that each got.

#51 Schema tool for reflective schema generation.
  README.md
  go.sum
  schema/README.md
  schema/commands/commands.go
  schema/docs/docs.go
  schema/example.go
  schema/example/schema.go
  schema/example_test.go
  schema/go.mod
  schema/go.sum
  schema/registry/registry.go
  schema/schema/generate_schema.go
  schema/schema/json_schema_props.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XXL

#53 Drop unnecessary occurrences of master
  README.md
  library.sh
  microbenchmarks.sh
Labels: approved, cla: yes, lgtm, size/S

#55 Don't redirect STDERR to /dev/null when querying pods
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#54 go test flags should go first
  e2e-tests.sh
  presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#58 [schema cli] correct arrays
  schema/commands/commands.go
  schema/example/schema.go
  schema/example_test.go
  schema/go.sum
  schema/schema/generate_schema.go
Labels: approved, cla: yes, lgtm, size/L

#60 Add a comment to explain why we have a long wait_until_pods_running function
  library.sh
Labels: approved, cla: yes, lgtm, size/XS
