Repository knative/hack, pull requests merged in 2021-06, with the labels that each got.

#70 Do not print debug info when running release.sh
  release.sh
Labels: approved, cla: yes, lgtm, size/XS

#72 Skip GOPATH hacks if the repository is already on GOPATH
  codegen-library.sh
  library.sh
Labels: approved, cla: yes, lgtm, size/S

#73 Rollback random GOBIN and make it relative to GOPATH again
  codegen-library.sh
Labels: approved, cla: yes, lgtm, size/XS

#48 Allow for ignoring arbitrary files with shellcheck
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#74 Cleanup release script more
  release.sh
Labels: approved, cla: yes, lgtm, size/S

#75 go-licenses fixed file permissions so we no longer need our workaround
  library.sh
Labels: approved, cla: yes, lgtm, size/XS

#76 update owner aliases manually
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#69 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
