Repository knative/hack, pull requests merged in 2022-07, with the labels that each got.

#195 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#197 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#199 remove references to markdown checking
  README.md
  test/unit/presubmit-tests.sh
Labels: lgtm, approved, size/S

#201 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#172 :broom: Migrate to using the `go run` instead of `go install`
  foo/output_test.go
  foo/short_test.go
  go.mod
  infra-library.sh
  library.sh
  presubmit-tests.sh
  release.sh
  test/e2e-kind.sh
  test/presubmit-tests.sh
  test/unit/test-helper.sh
Labels: lgtm, approved, size/L, kind/cleanup

#203 :bug: Fix the buoy invocation
  library.sh
Labels: lgtm, approved, size/XS, kind/bug

#204 drop warning in `go_run`
  library.sh
Labels: lgtm, approved, size/XS

#206 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
