Repository knative/hack, pull requests merged in 2022-05, with the labels that each got.

#173 Skip passing enable-ha flag to test script
  e2e-tests.sh
Labels: lgtm, approved, size/S

#175 Model []byte as strings
  schema/example/schema.go
  schema/example_test.go
  schema/schema/generate_schema.go
Labels: lgtm, approved, kind/bug, size/S

#177 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
