Repository knative/hack, pull requests merged in 2022-04, with the labels that each got.

#165 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#166 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#167 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#169 only use `install` for run_go_tool
  library.sh
Labels: lgtm, approved, size/S, kind/cleanup

#171 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
