Repository knative/hack, pull requests merged in 2022-09, with the labels that each got.

#217 :bug: Fixing go.mod foreach
  library.sh
Labels: lgtm, approved, size/XS, kind/bug

#215 :broom: Rewrite unit tests in Golang
  e2e-tests.sh
  infra-library.sh
  library.sh
  presubmit-tests.sh
  test/e2e-tests.sh
  test/library_test.go
  test/presubmit-tests.sh
  test/unit/.gitignore
  test/unit/e2e_helpers_test.go
  test/unit/library-tests.sh
  test/unit/library_test.go
  test/unit/presubmit-tests.sh
  test/unit/presubmit_test.go
  test/unit/release-tests.sh
  test/unit/release_test.go
  test/unit/report_go_test.go
  test/unit/run_e2e_test.go
  test/unit/scripts/exec-test-e2e-tests.bash
  test/unit/scripts/fake-dumps.bash
  test/unit/scripts/fake-prow-job.bash
  test/unit/scripts/smoke-test-custom-flag.bash
  test/unit/scripts/source-e2e-tests.bash
  test/unit/scripts/source-library.bash
  test/unit/scripts/source-presubmit-tests.bash
  test/unit/scripts/source-release.bash
  test/unit/sharedlib_test.go
  test/unit/test-helper.sh
  test/unit/update-deps-tests.sh
  test/unit/update_deps_test.go
Labels: size/XXL, lgtm, approved, kind/cleanup

#198 Start Signing our Releases
  go.work.sum
  release.sh
Labels: lgtm, approved, size/M

#224 Add flag to output image references
  release.sh
Labels: lgtm, approved, size/XS, kind/enhancement

#225 Default `SIGN_IMAGES` variable to `false`
  release.sh
Labels: lgtm, approved, size/XS

#227 :bug: Fix for test failures of knative/serving#13292
  e2e-tests.sh
  test/e2e-tests.sh
  test/unit/e2e_helpers_test.go
  test/unit/run_e2e_test.go
  test/unit/scripts/smoke-test-custom-flag.bash
  test/unit/sharedlib_test.go
Labels: lgtm, approved, kind/bug, size/M

#228 errexit and pipefail should remain off until downstream is fixed
  e2e-tests.sh
Labels: lgtm, approved, size/XS

#229 Output certificate when signing binaries
  release.sh
Labels: lgtm, approved, size/XS, kind/enhancement

#232 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
