Repository knative/hack, pull requests merged in 2022-11, with the labels that each got.

#239 [main] Format Go code
  test/unit/sharedlib_test.go
Labels: lgtm, approved, size/XS

#244 KO_DATA_PATH doesn't need to be set anymore
  e2e-tests.sh
Labels: lgtm, approved, size/XS

#245 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#243 drop support for the istio add on flag
  README.md
  e2e-tests.sh
  test/unit/presubmit_test.go
  test/unit/run_e2e_test.go
Labels: lgtm, approved, size/S

#247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#249 Trap calls are now executed in LIFO order
  library.sh
Labels: lgtm, approved, size/XS

#251 Calculate Image references properly
  release.sh
Labels: lgtm, approved, size/S

#253 [main] Format Go code
  schema/vendor/github.com/go-logr/logr/logr.go
  schema/vendor/github.com/gogo/protobuf/proto/lib.go
  schema/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  schema/vendor/github.com/json-iterator/go/iter_float.go
  schema/vendor/github.com/modern-go/reflect2/reflect2.go
  schema/vendor/github.com/modern-go/reflect2/type_map.go
  schema/vendor/github.com/modern-go/reflect2/unsafe_link.go
  schema/vendor/github.com/spf13/pflag/flag.go
  schema/vendor/github.com/spf13/pflag/string_slice.go
  schema/vendor/golang.org/x/net/http/httpguts/httplex.go
  schema/vendor/golang.org/x/net/http2/http2.go
  schema/vendor/golang.org/x/net/http2/server.go
  schema/vendor/golang.org/x/net/idna/trieval.go
  schema/vendor/golang.org/x/text/unicode/bidi/core.go
  schema/vendor/golang.org/x/text/unicode/norm/forminfo.go
  schema/vendor/golang.org/x/text/unicode/norm/normalize.go
  schema/vendor/gopkg.in/inf.v0/dec.go
  schema/vendor/gopkg.in/inf.v0/rounder.go
  schema/vendor/gopkg.in/yaml.v2/apic.go
  schema/vendor/gopkg.in/yaml.v2/emitterc.go
  schema/vendor/gopkg.in/yaml.v2/parserc.go
  schema/vendor/gopkg.in/yaml.v2/scannerc.go
  schema/vendor/gopkg.in/yaml.v2/yaml.go
  schema/vendor/gopkg.in/yaml.v2/yamlh.go
  schema/vendor/gopkg.in/yaml.v3/emitterc.go
  schema/vendor/gopkg.in/yaml.v3/parserc.go
  schema/vendor/gopkg.in/yaml.v3/scannerc.go
  schema/vendor/gopkg.in/yaml.v3/yaml.go
  schema/vendor/gopkg.in/yaml.v3/yamlh.go
  schema/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go
  schema/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  schema/vendor/k8s.io/apimachinery/pkg/labels/selector.go
  schema/vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  schema/vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go
  schema/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go
  schema/vendor/k8s.io/apimachinery/pkg/runtime/types.go
  schema/vendor/k8s.io/apimachinery/pkg/types/nodename.go
  schema/vendor/k8s.io/apimachinery/pkg/util/net/port_split.go
  schema/vendor/k8s.io/apimachinery/pkg/util/net/util.go
  schema/vendor/k8s.io/apimachinery/pkg/watch/filter.go
  schema/vendor/k8s.io/klog/v2/klog.go
  test/vendor/github.com/davecgh/go-spew/spew/config.go
  test/vendor/github.com/davecgh/go-spew/spew/doc.go
  test/vendor/github.com/davecgh/go-spew/spew/dump.go
  test/vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  test/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  test/vendor/github.com/stretchr/testify/assert/assertion_format.go
  test/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  test/vendor/github.com/stretchr/testify/assert/assertion_order.go
  test/vendor/github.com/stretchr/testify/assert/assertions.go
  test/vendor/github.com/stretchr/testify/assert/doc.go
  test/vendor/github.com/stretchr/testify/assert/http_assertions.go
  test/vendor/github.com/stretchr/testify/require/doc.go
  test/vendor/github.com/stretchr/testify/require/require.go
  test/vendor/github.com/stretchr/testify/require/require_forward.go
  test/vendor/gopkg.in/yaml.v3/emitterc.go
  test/vendor/gopkg.in/yaml.v3/parserc.go
  test/vendor/gopkg.in/yaml.v3/scannerc.go
  test/vendor/gopkg.in/yaml.v3/yaml.go
  test/vendor/gopkg.in/yaml.v3/yamlh.go
Labels: size/XXL, skip-review

#252 e2e script tweaks
  README.md
  e2e-tests.sh
  test/unit/e2e_helpers_test.go
Labels: lgtm, approved, size/M

#255 Allow tests to skip dumping resources on failure
  e2e-tests.sh
Labels: lgtm, approved, size/XS

#256 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#257 :bug: Don't use NodeLocalDNS addon
  e2e-tests.sh
  infra-library.sh
  test/unit/presubmit_test.go
Labels: lgtm, approved, kind/bug, size/S

#258 :bug: Revert of #257
  e2e-tests.sh
  test/unit/presubmit_test.go
Labels: lgtm, approved, size/XS, kind/bug
