Repository knative/hack, pull requests merged in 2022-01, with the labels that each got.

#137 :bug: No longer fail if teardown function isn't defined
  e2e-tests.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: lgtm, approved, kind/bug, size/S

#135 :bug: Proper search for tags in Go files only
  presubmit-tests.sh
Labels: lgtm, approved, kind/bug, size/M

#139 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#140 Print Commit Hashs on jobs.
  presubmit-tests.sh
Labels: lgtm, approved, size/XS

#143 Temporarily fix the unit tests for library.sh
  test/library_test.go
Labels: lgtm, approved, size/XS

#141 Cleanup unnecessary clusteradmin grants
  e2e-tests.sh
  infra-library.sh
Labels: lgtm, approved, size/S, kind/cleanup

#138 Disable Logs/Metrics on GKE and Run Preemptible Nodes
  infra-library.sh
Labels: lgtm, approved, size/XS

#142 Look at package name when checking whether the shell package can be used
  shell/project.go
Labels: lgtm, approved, size/S

#144 Enable opting out Preemptible/Spot GKE Worker Nodes
  README.md
  infra-library.sh
Labels: lgtm, approved, size/S

#145 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#146 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS
