Repository knative/hack, pull requests merged in 2022-10, with the labels that each got.

#231 Notarize Mac binaries
  release.sh
Labels: lgtm, approved, size/S

#234 Fix some bugs in the notarizing logic
  release.sh
Labels: lgtm, approved, size/XS

#235 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#236 Remove Signing Feature Gate
  release.sh
Labels: lgtm, approved, size/XS

#238 :gift: Use Knative ls-tags tool
  presubmit-tests.sh
  test/unit/sharedlib_test.go
Labels: lgtm, approved, kind/enhancement, size/L

#241 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
