Repository knative/hack, pull requests merged in 2023-02, with the labels that each got.

#267 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#265 Cleanup: remove ioutil for new go version
  shell/executor.go
  shell/project_test.go
Labels: lgtm, approved, size/XS, ok-to-test, needs-ok-to-test, kind/cleanup

#270 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#268 :bug: Location-agnostic sign release
  release.sh
  test/unit/release_test.go
  test/unit/scripts/fake-build-release.bash
  test/unit/scripts/fake-presubmit-tests.bash
  test/unit/sharedlib_test.go
Labels: lgtm, approved, kind/bug, size/L

#275 :bug: Find checksums file works with ARTIFACTS_TO_PUBLISH variable
  release.sh
  test/unit/release_test.go
Labels: lgtm, approved, kind/bug, size/M

#273 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#277 Set GitHub Release Title to the version of the release
  release.sh
Labels: lgtm, approved, size/XS
