Repository knative/hack, pull requests merged in 2023-05, with the labels that each got.

#286 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#292 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#291 Install Istio for e2e tests
  test/e2e-kind.sh
Labels: lgtm, approved, size/M

#289 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/S, skip-review
