Repository knative/hack, pull requests merged in 2023-08, with the labels that each got.

#304 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, skip-review

#293 Added knative-extensions
  library.sh
Labels: lgtm, approved, size/XS

#305 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#306 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#308 manual rename
  test/e2e-kind.sh
Labels: lgtm, approved, size/XS

#309 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#230 Deprecate calling kubetest2 via kntest
  e2e-tests.sh
  infra-library.sh
  performance-tests.sh
  presubmit-tests.sh
  test/e2e-tests.sh
  test/unit/presubmit_test.go
  test/unit/sharedlib_test.go
Labels: lgtm, approved, size/M
