Repository knative/hack, pull requests merged in 2023-09, with the labels that each got.

#314 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#316 :bug: Collect LICENSE files from all dependencies, even without vendor dir
  go.work.sum
  library.sh
  schema/third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/gogo/protobuf/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/google/gofuzz/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/json-iterator/go/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/modern-go/concurrent/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/modern-go/reflect2/LICENSE
  schema/third_party/VENDOR-LICENSE/github.com/spf13/cobra/LICENSE.txt
  schema/third_party/VENDOR-LICENSE/github.com/spf13/pflag/LICENSE
  schema/third_party/VENDOR-LICENSE/golang.org/x/net/LICENSE
  schema/third_party/VENDOR-LICENSE/golang.org/x/text/LICENSE
  schema/third_party/VENDOR-LICENSE/gopkg.in/inf.v0/LICENSE
  schema/third_party/VENDOR-LICENSE/gopkg.in/yaml.v2/LICENSE
  schema/third_party/VENDOR-LICENSE/gopkg.in/yaml.v2/NOTICE
  schema/third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/LICENSE
  schema/third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/NOTICE
  schema/third_party/VENDOR-LICENSE/k8s.io/apimachinery/LICENSE
  schema/third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  schema/third_party/VENDOR-LICENSE/knative.dev/hack/schema/LICENSE
  schema/third_party/VENDOR-LICENSE/sigs.k8s.io/structured-merge-diff/v4/value/LICENSE
  third_party/VENDOR-LICENSE/github.com/pkg/errors/LICENSE
  third_party/VENDOR-LICENSE/github.com/spf13/cobra/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/spf13/pflag/LICENSE
  third_party/VENDOR-LICENSE/github.com/wavesoftware/go-commandline/LICENSE
  third_party/VENDOR-LICENSE/github.com/wavesoftware/go-retcode/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/hack/LICENSE
Labels: size/XXL, lgtm, approved, kind/bug

#317 :bug: The `go.work.sum` don't influence the dependencies resolution
  go.mod
  go.sum
  go.work.sum
  library.sh
  schema/go.mod
  schema/go.sum
  test/go.mod
  test/go.sum
  test/unit/update_deps_test.go
  test/vendorproj/go.mod
  test/vendorproj/go.sum
  test/vendorproj/vendor/modules.txt
Labels: lgtm, approved, size/XL, kind/bug

#319 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#320 :bug: Remove deps from go.mod for knative.dev/hack
  cmd/script/main.go
  cmd/script/main_test.go
  embed.go
  embed_test.go
  go.mod
  go.sum
  pkg/constraints/types.go
  pkg/inflator/cli/app.go
  pkg/inflator/cli/app_test.go
  pkg/inflator/cli/exec.go
  pkg/inflator/cli/flags.go
  pkg/inflator/cli/print.go
  pkg/inflator/cli/usage.go
  pkg/inflator/extract/errors.go
  pkg/inflator/extract/extract.go
  pkg/inflator/extract/extract_test.go
  pkg/retcode/retcode.go
  pkg/utest/assert/contain.go
  pkg/utest/assert/equal.go
  pkg/utest/assert/error.go
  pkg/utest/assert/format.go
  pkg/utest/assert/testingt.go
  pkg/utest/require/error.go
  pkg/utest/require/testingt.go
  test/go.mod
  test/go.sum
  test/no_deps_test.go
  third_party/VENDOR-LICENSE/github.com/pkg/errors/LICENSE
  third_party/VENDOR-LICENSE/github.com/spf13/cobra/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/spf13/pflag/LICENSE
  third_party/VENDOR-LICENSE/github.com/wavesoftware/go-commandline/LICENSE
  third_party/VENDOR-LICENSE/github.com/wavesoftware/go-retcode/LICENSE
Labels: size/XXL, lgtm, approved, kind/bug

#321 Manual shellcheck
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/S

#323 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/M, skip-review

#324 :gift: Docs on using vendorless Knative projects
  README.md
  cmd/script/README.md
Labels: lgtm, approved, size/M, kind/documentation
