Repository knative/hack, pull requests merged in 2023-01, with the labels that each got.

#261 Upload attestations and print cosign version
  presubmit-tests.sh
  release.sh
  test/unit/sharedlib_test.go
Labels: lgtm, approved, size/XS

#262 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#263 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
