Repository knative/hack, pull requests merged in 2023-04, with the labels that each got.

#281 Revert "Extract tools to knative.dev/toolbox (#280)"
  library.sh
  presubmit-tests.sh
  test/unit/presubmit_test.go
  test/unit/sharedlib_test.go
  test/unit/update_deps_test.go
Labels: lgtm, approved, size/S

#282 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#283 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#284 Fix bug that broke signatures
  release.sh
Labels: lgtm, approved, size/XS

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
