Repository knative/hack, pull requests merged in 2023-11, with the labels that each got.

#339 add function to set latest semver to latest
  release.sh
Labels: lgtm, approved, size/S

#343 :bug: Call set_latest_to_highest_semver after publishing a new release
  release.sh
Labels: lgtm, approved, size/XS, kind/bug

#346 :bug: Set latest release only when publishing to Github
  release.sh
Labels: lgtm, approved, kind/bug, size/S

#350 Adding the variable `KNATIVE_EVENTING_RELEASE_TLS` to install latest eventing TLS
  library.sh
Labels: lgtm, approved, size/XS

#354 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
