Repository knative/hack, pull requests merged in 2024-03, with the labels that each got.

#371 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#372 bump various tools
  library.sh
  test/unit/presubmit_test.go
Labels: lgtm, approved, size/XS

#373 switch default region to avoid instability
  infra-library.sh
Labels: lgtm, approved, size/XS

#374 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#326 :bug: Call `go mod download` on each module, if not vendor
  go.work.sum
  library.sh
Labels: lgtm, approved, kind/bug, size/M

#349 Make SECURITY.md consistent
  SECURITY.md
Labels: lgtm, approved, size/XS

#353 Add clotributor link to readme
  README.md
Labels: lgtm, approved, size/XS

#377 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#376 :broom: Check licenses only, but not bundle them
  library.sh
  test/unit/update_deps_test.go
Labels: lgtm, approved, size/S, kind/cleanup
